# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 717de8564f296f77fb86b7a21e514a6198b007e2de359375a761fbfcbd9bcb104bd4b5c1923d395e9f5d22b71ff1870119eb5514434c9ba8802bc7a62334e418

test:
  secret_key_base: e11ebb646765b86e46de1fbfab7571d2f051a1d0633ae6e8c60beee9aacd184589e903b9979d48fbb4056c9e04826cb6a2fe8d21dc93862e3f05683e053ecde1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
